apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kakfa-trigger
  annotations:
     kafka.eventing.knative.dev/delivery.order: ordered
spec:
  broker: kafka-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
